spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8

jpa:
    show-sql: true
jackson:
    default-property-inclusion: non_null
redis:
    host: 192.168.30.113
    port: 6379
server:
  context-path: /sell

#定义日志文件位置和日志文件名，默认位置src/main/resource,默认名称：https://blog.csdn.net/inke88/article/details/75007649
logging:
  config: classpath:LogConfig/logback-test.xml
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/LogConfig/tomcat/
#  LogConfig: /var/LogConfig/tomcat/sell.LogConfig
#  level:
#    com.csk.LoggerTest: debug

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc

#mybatis:
#  mapper-locations: classpath:mapper/*.xml